### ISSUE TITLE
no proper output

### ISSUE THREAD

**Issue by Mjagriti** [narekum/VSvina#2]
mode |   affinity | dist from best mode
             | (kcal/mol) | rmsd l.b.| rmsd u.b.
DB00171 -----+------------+----------+----------        adenosine       triphosphate
DB00619 -----+------------+----------+----------        imatinib
DB08881 -----+------------+----------+----------        vemurafenib
DB00131 -----+------------+----------+----------        adenylate
after running vsvina command, output is without values.

**Comment by narekum** [comment]
A little description and possibly posting input files will be helpful
